Repository Realfsen/foodblog, pull requests merged in 2020-11, with the labels that each got.

#44 CSS relocation
  Site/baking101.html
  Site/contact.html
  Site/content.html
  Site/index.html
  Site/js/modularity_head.js
  Site/recipe_list.html
Labels: quick fix

#49 Stian alpha feedback corrections
  Site/recipe_list.html
Labels: quick fix

#51 Stian no alert form
  Site/contact.html
  Site/js/form.js
Labels: enhancement

#54 Develop
  Documents/IT2805_UserTesting.pdf
  Documents/P3_changes_56.html
  Documents/UserTesting_images/Access_the_site.png
  Documents/UserTesting_images/Navigation_Score.png
  Documents/UserTesting_images/Pages_viewed.png
  Documents/UserTesting_images/Tried_contact_form.png
  Documents/UserTesting_images/User_Age.png
  Documents/UserTesting_images/User_Browser.png
  Documents/UserTesting_images/User_Device.png
  Documents/UserTesting_images/User_Experience.png
  Documents/UserTesting_images/User_Gender.png
  Documents/UserTesting_images/User_Interest.png
  Documents/UserTesting_images/Website_total_score.png
  Site/baking101.html
  Site/contact.html
  Site/content.html
  Site/index.html
  Site/js/contentFromUrl.js
  Site/js/form.js
  Site/js/jsonLoader.js
  Site/js/recipeRetriever.js
  Site/js/slideshow.js
  Site/recipe_list.html
Labels: documentation, enhancement
