Repository Realfsen/foodblog, pull requests merged in 2020-10, with the labels that each got.

#7 Update P2_design_56.html
  Documents/P2_design_56.html
Labels: documentation

#11 Contact - development
  Site/contact.html
  Site/css/style.css
  Site/img/ContactUsImage.png
  Site/js/form.js
Labels: enhancement

#15 JS for head, header, and footer.
  Site/contact.html
  Site/css/style.css
  Site/img/Kun_logo.png
  Site/img/Kun_logo_hvit.png
  Site/img/favicons/android-chrome-192x192.png
  Site/img/favicons/android-chrome-512x512.png
  Site/img/favicons/apple-touch-icon.png
  Site/img/favicons/browserconfig.xml
  Site/img/favicons/favicon-16x16.png
  Site/img/favicons/favicon-32x32.png
  Site/img/favicons/favicon.ico
  Site/img/favicons/mstile-150x150.png
  Site/img/favicons/safari-pinned-tab.svg
  Site/img/favicons/site.webmanifest
  Site/js/form.js
  Site/js/modularity.js
  Site/js/modularity_head.js
Labels: enhancement

#27 Updates to footer CSS
  Site/baking101.html
  Site/contact.html
  Site/css/style.css
  Site/index.html
  Site/recipe_list.html
Labels: enhancement

#42 ny js for tittel på cards-sider, pluss småfiks inkl sjokkokake
  Site/content.html
  Site/js/title.js
  Site/recipes/Cake.json
  Site/recipes/Sjokoladekake.json
  Site/recipes/recipes.json
Labels: Feature
